name: Build and publish
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Publish build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - uses: actions/deploy-pages@v1.2.3
        with:
          artifact_name: dist
